/**
 * Core partner registry referenced by the explorer and directory views.
 * Projects hydrate additional analytics (missions, roles, counts) at runtime.
 */
window.partners = [
  {
    id: "infordata",
    name: "Infordata SRL",
    acronym: "INFD",
    country: "Italy",
    type: "SME",
    website: "https://infordata.eu",
    focus: "Data platforms for blue mission monitoring and citizen observatories.",
    specialties: ["Digital twins", "Nature-based solutions", "Citizen engagement"],
  },
  {
    id: "university-of-crete",
    name: "University of Crete",
    acronym: "UOC",
    country: "Greece",
    type: "University",
    website: "https://www.uoc.gr",
    focus: "Marine ecology, restoration ecology, and coastal climate adaptation.",
    specialties: ["Marine biodiversity", "Coastal adaptation"],
  },
  {
    id: "ecomarine-spain",
    name: "EcoMarine Spain",
    acronym: "EMS",
    country: "Spain",
    type: "NGO",
    website: "https://ecomarinespain.org",
    focus: "Community-led coastal clean-ups and ocean literacy programming.",
    specialties: ["Citizen science", "Coastal stewardship"],
  },
  {
    id: "lisbon-science-museum",
    name: "Lisbon Science Museum",
    acronym: "MUCI",
    country: "Portugal",
    type: "Cultural Institution",
    website: "https://www.museudaciencia.pt",
    focus: "Immersive science experiences linking ocean literacy and climate action.",
    specialties: ["Ocean literacy", "Public engagement"],
  },
  {
    id: "port-of-antwerp",
    name: "Port of Antwerp-Bruges Authority",
    acronym: "PoAB",
    country: "Belgium",
    type: "Port Authority",
    website: "https://www.portofantwerpbruges.com",
    focus: "Large-scale port infrastructure, logistics innovation, and decarbonisation.",
    specialties: ["Zero-emission ports", "Circular logistics"],
  },
  {
    id: "blue-tech-netherlands",
    name: "BlueTech Netherlands",
    acronym: "BTN",
    country: "Netherlands",
    type: "SME",
    website: "https://bluetechnl.eu",
    focus: "Hydrogen systems integration and smart energy retrofits for ports.",
    specialties: ["Hydrogen systems", "Smart grid"],
  },
  {
    id: "glasgow-digital-labs",
    name: "Glasgow Maritime Digital Labs",
    acronym: "GMDL",
    country: "United Kingdom",
    type: "Research Centre",
    website: "https://gmdl.ac.uk",
    focus: "Immersive training platforms and maritime digital twin R&D.",
    specialties: ["Digital twins", "XR training"],
  },
  {
    id: "porto-engineering-school",
    name: "Porto Engineering School",
    acronym: "ISEP",
    country: "Portugal",
    type: "University",
    website: "https://www.isep.ipp.pt",
    focus: "Applied engineering for resilient coastal infrastructure.",
    specialties: ["Coastal engineering", "Circular design"],
  },
  {
    id: "helsinki-university",
    name: "Helsinki University of Technology",
    acronym: "HUT",
    country: "Finland",
    type: "University",
    website: "https://www.aalto.fi",
    focus: "Autonomous sensing, data fusion, and climate analytics for Baltic waters.",
    specialties: ["Autonomous sensing", "Eutrophication modelling"],
  },
  {
    id: "baltic-research-alliance",
    name: "Baltic Research Alliance",
    acronym: "BRA",
    country: "Sweden",
    type: "Research Network",
    website: "https://balticalliance.org",
    focus: "Coordinating transnational nutrient reduction strategies.",
    specialties: ["Nutrient management", "Policy integration"],
  },
  {
    id: "greenchem-poland",
    name: "GreenChem Poland",
    acronym: "GCP",
    country: "Poland",
    type: "SME",
    website: "https://greenchem.pl",
    focus: "Green chemistry solutions for agricultural runoff and industrial discharges.",
    specialties: ["Green chemistry", "Nutrient capture"],
  },
  {
    id: "tallinn-startup-hub",
    name: "Tallinn Blue Startup Hub",
    acronym: "TBSH",
    country: "Estonia",
    type: "Incubator",
    website: "https://tbsh.ee",
    focus: "Accelerating blue-tech ventures and AI monitoring startups.",
    specialties: ["Startup acceleration", "AI monitoring"],
  },
  {
    id: "danube-innovation-hub",
    name: "Danube Innovation Hub",
    acronym: "DIH",
    country: "Austria",
    type: "Cluster",
    website: "https://danubehub.eu",
    focus: "Circular aquaculture, regional innovation ecosystems, and blue skills.",
    specialties: ["Aquaculture", "Cluster development"],
  },
  {
    id: "vienna-analytics-lab",
    name: "Vienna Blue Analytics Lab",
    acronym: "VBAL",
    country: "Austria",
    type: "Research Centre",
    website: "https://vbal.at",
    focus: "Data-driven optimisation for aquaculture and bioresource valorisation.",
    specialties: ["Predictive analytics", "Bioresource modelling"],
  },
  {
    id: "balkan-maritime-cluster",
    name: "Balkan Maritime Cluster",
    acronym: "BMC",
    country: "Bulgaria",
    type: "Cluster",
    website: "https://bmc.bg",
    focus: "Transnational maritime SME collaboration across the Black Sea and Danube.",
    specialties: ["SME networking", "Blue value chains"],
  },
  {
    id: "belgrade-aqua-startups",
    name: "Belgrade Aqua Startups",
    acronym: "BAS",
    country: "Serbia",
    type: "Incubator",
    website: "https://bas.rs",
    focus: "Incubating blue biotech and circular aquaculture ventures.",
    specialties: ["Blue biotech", "Startup incubation"],
  },
  {
    id: "nordic-marine-systems",
    name: "Nordic Marine Systems",
    acronym: "NMS",
    country: "Norway",
    type: "SME",
    website: "https://nordicmarine.no",
    focus: "Autonomous robotics and edge analytics for extreme marine environments.",
    specialties: ["Autonomous systems", "Edge computing"],
  },
  {
    id: "polar-research-institute",
    name: "Polar Research Institute",
    acronym: "PRI",
    country: "Iceland",
    type: "Research Institute",
    website: "https://pri.is",
    focus: "Polar oceanography and emergency response coordination.",
    specialties: ["Polar science", "Emergency response"],
  },
  {
    id: "oslo-maritime-college",
    name: "Oslo Maritime College",
    acronym: "OMC",
    country: "Norway",
    type: "University",
    website: "https://omc.no",
    focus: "Maritime safety, crew training, and alternative propulsion systems.",
    specialties: ["Maritime safety", "Alternative propulsion"],
  },
  {
    id: "greenfleet-denmark",
    name: "GreenFleet Denmark",
    acronym: "GFD",
    country: "Denmark",
    type: "Industry Association",
    website: "https://greenfleet.dk",
    focus: "Decarbonising Nordic shipping corridors and port operations.",
    specialties: ["Decarbonisation", "Fleet transition"],
  },
  {
    id: "aegean-shipyards",
    name: "Aegean Shipyards Cooperative",
    acronym: "ASC",
    country: "Greece",
    type: "Industry Consortium",
    website: "https://aegeanshipyards.gr",
    focus: "Hybrid vessel retrofits, hydrogen bunkering, and island logistics.",
    specialties: ["Shipbuilding", "Hydrogen retrofits"],
  },
  {
    id: "crete-energy-lab",
    name: "Crete Energy Lab",
    acronym: "CEL",
    country: "Greece",
    type: "Research Centre",
    website: "https://cel.gr",
    focus: "Hydrogen energy systems and smart grids for island communities.",
    specialties: ["Hydrogen systems", "Smart grids"],
  },
  {
    id: "blue-islands-tourism",
    name: "Blue Islands Tourism Board",
    acronym: "BITB",
    country: "Greece",
    type: "Public Agency",
    website: "https://blueislands.gr",
    focus: "Blue tourism transition, awareness campaigns, and stakeholder mobilization.",
    specialties: ["Sustainable tourism", "Stakeholder engagement"],
  },
  {
    id: "northsea-cleanup",
    name: "North Sea Cleanup Alliance",
    acronym: "NSCA",
    country: "Netherlands",
    type: "NGO",
    website: "https://nscleanup.eu",
    focus: "River-to-sea plastic interception, recycling ecosystems, and local mobilisation.",
    specialties: ["Plastic interception", "Circular plastics"],
  },
  {
    id: "scottish-marine-institute",
    name: "Scottish Marine Institute",
    acronym: "SMI",
    country: "United Kingdom",
    type: "Research Institute",
    website: "https://smi.ac.uk",
    focus: "Marine ecology, fisheries data science, and citizen science coordination.",
    specialties: ["Marine ecology", "Citizen science"],
  },
  {
    id: "hamburg-circular-tech",
    name: "Hamburg Circular Tech",
    acronym: "HCT",
    country: "Germany",
    type: "SME",
    website: "https://hct.de",
    focus: "Circular economy technologies and AI-driven waste valorisation.",
    specialties: ["Circular economy", "AI analytics"],
  },
  {
    id: "ocean-citizens-network",
    name: "Ocean Citizens Network",
    acronym: "OCN",
    country: "Netherlands",
    type: "Civil Society",
    website: "https://oceancitizens.eu",
    focus: "Grassroots mobilisation, community observatories, and youth programmes.",
    specialties: ["Citizen mobilisation", "Youth programmes"],
  },
  {
    id: "barcelona-digital-ocean-hub",
    name: "Barcelona Digital Ocean Hub",
    acronym: "BDOH",
    country: "Spain",
    type: "Innovation Hub",
    website: "https://barcelonadoceanhub.org",
    focus: "Urban ocean living labs, blue health, and civic tech for the coasts.",
    specialties: ["Living labs", "Blue health"],
  },
  {
    id: "porto-blue-health",
    name: "Porto Blue Health Institute",
    acronym: "PBHI",
    country: "Portugal",
    type: "Research Institute",
    website: "https://pbhi.pt",
    focus: "Blue health analytics, citizen science data quality, and coastal wellbeing.",
    specialties: ["Blue health", "Citizen science"],
  },
];
