/**
 * TASC-RestoreMed mock dataset for EU Mission projects.
 * Each project captures cross-cutting dimensions used by the explorer UI.
 */
window.projects = [
  {
    id: "PRJ-2024-001",
    title: "Mediterranean Coastal Restoration Initiative",
    acronym: "MedCoastRestore",
    status: "Active",
    startDate: "2024-01-15",
    endDate: "2026-12-31",
    startYear: 2024,
    missionZone: "Mediterranean",
    leadPartner: "Infordata SRL",
    leadCountry: "Italy",
    missionPillars: ["Environmental", "Biodiversity", "Human Health"],
    missionObjectives: [
      "Protect & restore marine and coastal ecosystems and biodiversity (Patrizio Mariani)",
      "Prevent pollution – litter & microplastics (Luisa Galgani)",
    ],
    topicClusters: ["Habitat restoration", "Pollution remediation"],
    technologyPillars: ["Prevention", "Monitoring"],
    summary:
      "Co-designs restoration blueprints, deploys AI-driven coastal monitoring buoys, and mobilises citizen labs to regenerate degraded Mediterranean shorelines.",
    funding: "Horizon Europe · Mission Restore our Oceans & Waters",
    budget: "€5.2M",
    missionKpis: ["Restored area (ha)", "Stakeholders trained", "Microplastic concentration (items/m³)"],
    keywords: ["coastal resilience", "nature-based solutions", "citizen science"],
    website: "https://medcoastrestore.eu",
    partners: [
      { id: "infordata", name: "Infordata SRL", acronym: "INFD", country: "Italy", type: "SME", role: "Lead", website: "https://infordata.eu" },
      { id: "university-of-crete", name: "University of Crete", acronym: "UOC", country: "Greece", type: "University", role: "Partner", website: "https://www.uoc.gr" },
      { id: "ecomarine-spain", name: "EcoMarine Spain", acronym: "EMS", country: "Spain", type: "NGO", role: "Partner", website: "https://ecomarinespain.org" },
      {
        id: "lisbon-science-museum",
        name: "Lisbon Science Museum",
        acronym: "MUCI",
        country: "Portugal",
        type: "Cultural Institution",
        role: "Partner",
        website: "https://www.museudaciencia.pt",
      },
    ],
    insights: {
      technologyHighlights: ["Edge AI monitoring buoys", "Lidar shoreline surveys"],
      engagementActions: ["Open coastal hackathons", "Schools ocean literacy labs"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€4.6M",
      missionZoneFocus: "12 pilot coastal sites",
      technologyFocus: "AI-enabled monitoring & NBS",
    },
  },
  {
    id: "PRJ-2023-014",
    title: "Atlantic Smart Ports Coalition",
    acronym: "ASPC",
    status: "Ongoing",
    startDate: "2023-04-01",
    endDate: "2025-09-30",
    startYear: 2023,
    missionZone: "Atlantic",
    leadPartner: "Port of Antwerp-Bruges Authority",
    leadCountry: "Belgium",
    missionPillars: ["Climate", "Economic Impact", "Education & Social Engagement"],
    missionObjectives: [
      "Blue economy – multiuse of water space (Pierre Failler)",
      "Blue economy – decarbonisation of maritime industries (Markus Lehne)",
      "Raising awareness (Philippe Vallette)",
    ],
    topicClusters: ["Zero-discharge ports", "Digital Twins"],
    technologyPillars: ["Prevention", "Monitoring"],
    summary:
      "Retrofits Atlantic ports with circular wastewater systems, hybrid energy microgrids, and immersive training for zero-discharge operations.",
    funding: "CEF Transport · Mission Ocean Synergy Grant",
    budget: "€7.8M",
    missionKpis: ["Port emission intensity", "Zero-discharge compliance rate", "Workers certified"],
    keywords: ["smart ports", "sensor networks", "clean shipping"],
    website: "https://atlantic-smartports.eu",
    partners: [
      {
        id: "port-of-antwerp",
        name: "Port of Antwerp-Bruges Authority",
        acronym: "PoAB",
        country: "Belgium",
        type: "Port Authority",
        role: "Lead",
        website: "https://www.portofantwerpbruges.com",
      },
      { id: "blue-tech-netherlands", name: "BlueTech Netherlands", acronym: "BTN", country: "Netherlands", type: "SME", role: "Partner", website: "https://bluetechnl.eu" },
      { id: "glasgow-digital-labs", name: "Glasgow Maritime Digital Labs", acronym: "GMDL", country: "United Kingdom", type: "Research Centre", role: "Partner", website: "https://gmdl.ac.uk" },
      {
        id: "porto-engineering-school",
        name: "Porto Engineering School",
        acronym: "ISEP",
        country: "Portugal",
        type: "University",
        role: "Partner",
        website: "https://www.isep.ipp.pt",
      },
    ],
    insights: {
      technologyHighlights: ["Digital twin for tidal forecasts", "Hydrogen bunkering optimisation"],
      engagementActions: ["VR safety training", "Open port innovation days"],
    },
    comparison: {
      durationMonths: 30,
      euContribution: "€6.1M",
      missionZoneFocus: "6 core Atlantic ports",
      technologyFocus: "Hydrogen hybridisation",
    },
  },
  {
    id: "PRJ-2023-021",
    title: "Baltic Nutrient Watch",
    acronym: "BalticWatch",
    status: "Active",
    startDate: "2023-02-15",
    endDate: "2026-02-14",
    startYear: 2023,
    missionZone: "Baltic Sea",
    leadPartner: "Helsinki University of Technology",
    leadCountry: "Finland",
    missionPillars: ["Environmental", "Climate", "Human Health"],
    missionObjectives: [
      "Prevent pollution – nutrients, chemicals, pesticides (Teresa Rocha Santos)",
      "Ocean digital knowledge system (Magdalena Matczak)",
    ],
    topicClusters: ["AI-based monitoring", "Digital Twins"],
    technologyPillars: ["Monitoring"],
    summary:
      "Deploys autonomous nutrient probes, integrates riverine datasets, and predicts eutrophication hotspots for faster remediation actions.",
    funding: "Interreg Baltic Sea Region · Mission Lighthouse",
    budget: "€4.1M",
    missionKpis: ["Nutrient load reduction (t)", "Alerts issued", "Restoration plans activated"],
    keywords: ["eutrophication", "autonomous sensors", "predictive analytics"],
    website: "https://balticwatch.eu",
    partners: [
      { id: "helsinki-university", name: "Helsinki University of Technology", acronym: "HUT", country: "Finland", type: "University", role: "Lead", website: "https://www.aalto.fi" },
      {
        id: "baltic-research-alliance",
        name: "Baltic Research Alliance",
        acronym: "BRA",
        country: "Sweden",
        type: "Research Network",
        role: "Partner",
        website: "https://balticalliance.org",
      },
      { id: "greenchem-poland", name: "GreenChem Poland", acronym: "GCP", country: "Poland", type: "SME", role: "Partner", website: "https://greenchem.pl" },
      { id: "tallinn-startup-hub", name: "Tallinn Blue Startup Hub", acronym: "TBSH", country: "Estonia", type: "Incubator", role: "Partner", website: "https://tbsh.ee" },
    ],
    insights: {
      technologyHighlights: ["Autonomous surface gliders", "Bayesian plume modelling"],
      engagementActions: ["Farmer nutrient advisory labs", "Baltic schools monitoring kits"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€3.4M",
      missionZoneFocus: "15 nutrient catchments",
      technologyFocus: "Autonomous monitoring mesh",
    },
  },
  {
    id: "PRJ-2025-005",
    title: "Danube Blue Bioeconomy Accelerator",
    acronym: "BlueBioAccel",
    status: "Active",
    startDate: "2025-03-01",
    endDate: "2028-02-28",
    startYear: 2025,
    missionZone: "Danube Basin",
    leadPartner: "Danube Innovation Hub",
    leadCountry: "Austria",
    missionPillars: ["Economic Impact", "Education & Social Engagement", "Environmental"],
    missionObjectives: [
      "Blue economy – carbon-neutral & circular aquaculture (Katerina Moutou)",
      "Mobilization & engagement (Giovanna Chimini)",
      "Protect & restore marine and freshwater ecosystems and biodiversity (Isabel Sousa Pinto)",
    ],
    topicClusters: ["Blue biotech", "Sustainable tourism"],
    technologyPillars: ["Prevention", "Collection"],
    summary:
      "Scales circular aquaculture pilots, valorises by-products into blue biotech ventures, and trains youth labs along the Danube corridor.",
    funding: "Horizon Europe · Mission Innovation Action",
    budget: "€6.4M",
    missionKpis: ["Aquaculture emissions (kg CO₂e/kg)", "Spin-offs created", "Tourism operators onboarded"],
    keywords: ["bioeconomy", "aquaculture", "circular value chains"],
    website: "https://danubebluebio.eu",
    partners: [
      { id: "danube-innovation-hub", name: "Danube Innovation Hub", acronym: "DIH", country: "Austria", type: "Cluster", role: "Lead", website: "https://danubehub.eu" },
      {
        id: "vienna-analytics-lab",
        name: "Vienna Blue Analytics Lab",
        acronym: "VBAL",
        country: "Austria",
        type: "Research Centre",
        role: "Partner",
        website: "https://vbal.at",
      },
      { id: "balkan-maritime-cluster", name: "Balkan Maritime Cluster", acronym: "BMC", country: "Bulgaria", type: "Cluster", role: "Partner", website: "https://bmc.bg" },
      { id: "belgrade-aqua-startups", name: "Belgrade Aqua Startups", acronym: "BAS", country: "Serbia", type: "Incubator", role: "Partner", website: "https://bas.rs" },
    ],
    insights: {
      technologyHighlights: ["Recirculating aquaculture platforms", "Biopolymer extraction units"],
      engagementActions: ["Danube youth innovation sprints", "Blue bioeconomy roadshows"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€5.1M",
      missionZoneFocus: "7 Danube regions",
      technologyFocus: "Circular aquaculture systems",
    },
  },
  {
    id: "PRJ-2022-032",
    title: "Arctic Polar Sentinel",
    acronym: "APS",
    status: "Ongoing",
    startDate: "2022-06-01",
    endDate: "2025-05-31",
    startYear: 2022,
    missionZone: "Arctic & North Atlantic",
    leadPartner: "Nordic Marine Systems",
    leadCountry: "Norway",
    missionPillars: ["Climate", "Environmental", "Human Health"],
    missionObjectives: [
      "Ocean digital knowledge system (Magdalena Matczak)",
      "Blue economy – decarbonisation of maritime industries (Markus Lehne)",
    ],
    topicClusters: ["AI-based monitoring", "Digital Twins"],
    technologyPillars: ["Monitoring"],
    summary:
      "Combines satellite SAR, autonomous under-ice drones, and edge analytics to detect oil spills and anticipate shipping risks in polar waters.",
    funding: "Eureka Eurostars · Mission Cross-Cooperation",
    budget: "€3.9M",
    missionKpis: ["Spill detection time (hrs)", "Voyages decarbonised", "Alerts delivered"],
    keywords: ["polar monitoring", "edge AI", "decarbonisation"],
    website: "https://arcticpolarsentinel.org",
    partners: [
      { id: "nordic-marine-systems", name: "Nordic Marine Systems", acronym: "NMS", country: "Norway", type: "SME", role: "Lead", website: "https://nordicmarine.no" },
      { id: "polar-research-institute", name: "Polar Research Institute", acronym: "PRI", country: "Iceland", type: "Research Institute", role: "Partner", website: "https://pri.is" },
      { id: "oslo-maritime-college", name: "Oslo Maritime College", acronym: "OMC", country: "Norway", type: "University", role: "Partner", website: "https://omc.no" },
      { id: "greenfleet-denmark", name: "GreenFleet Denmark", acronym: "GFD", country: "Denmark", type: "Industry Association", role: "Partner", website: "https://greenfleet.dk" },
    ],
    insights: {
      technologyHighlights: ["Under-ice autonomy", "Edge anomaly detection"],
      engagementActions: ["Polar shipping decarbonisation clinics", "Arctic emergency drills"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€2.9M",
      missionZoneFocus: "High Arctic corridors",
      technologyFocus: "Under-ice monitoring",
    },
  },
  {
    id: "PRJ-2021-018",
    title: "Aegean Net Zero Ferries",
    acronym: "ANZF",
    status: "Completed",
    startDate: "2021-02-01",
    endDate: "2023-07-31",
    startYear: 2021,
    missionZone: "Aegean Archipelago",
    leadPartner: "Aegean Shipyards Cooperative",
    leadCountry: "Greece",
    missionPillars: ["Climate", "Economic Impact", "Education & Social Engagement"],
    missionObjectives: [
      "Blue economy – decarbonisation of maritime industries (Markus Lehne)",
      "Mobilization & engagement (Giovanna Chimini)",
    ],
    topicClusters: ["Zero-discharge ports", "Sustainable tourism"],
    technologyPillars: ["Prevention"],
    summary:
      "Converted island ferry lines to hybrid hydrogen-electric fleets, supported clean port retrofits, and launched travel campaigns for low-carbon tourism.",
    funding: "CEF Transport · Mission Demonstration",
    budget: "€8.3M",
    missionKpis: ["CO₂ saved (t)", "Green tourists reached", "Ports retrofitted"],
    keywords: ["zero emission ferries", "hydrogen", "green tourism"],
    website: "https://netzeroferries.eu",
    partners: [
      { id: "aegean-shipyards", name: "Aegean Shipyards Cooperative", acronym: "ASC", country: "Greece", type: "Industry Consortium", role: "Lead", website: "https://aegeanshipyards.gr" },
      {
        id: "crete-energy-lab",
        name: "Crete Energy Lab",
        acronym: "CEL",
        country: "Greece",
        type: "Research Centre",
        role: "Partner",
        website: "https://cel.gr",
      },
      { id: "oslo-maritime-college", name: "Oslo Maritime College", acronym: "OMC", country: "Norway", type: "University", role: "Partner", website: "https://omc.no" },
      { id: "blue-islands-tourism", name: "Blue Islands Tourism Board", acronym: "BITB", country: "Greece", type: "Public Agency", role: "Partner", website: "https://blueislands.gr" },
    ],
    insights: {
      technologyHighlights: ["Hydrogen bunkering corridors", "Smart ferry energy management"],
      engagementActions: ["Island transition labs", "Tourism decarbonisation campaigns"],
    },
    comparison: {
      durationMonths: 30,
      euContribution: "€6.0M",
      missionZoneFocus: "11 island routes",
      technologyFocus: "Hydrogen-electric ferries",
    },
  },
  {
    id: "PRJ-2024-011",
    title: "North Sea Plastic Sweep",
    acronym: "PlastiSweep",
    status: "Active",
    startDate: "2024-03-01",
    endDate: "2027-02-28",
    startYear: 2024,
    missionZone: "North Sea",
    leadPartner: "North Sea Cleanup Alliance",
    leadCountry: "Netherlands",
    missionPillars: ["Environmental", "Human Health", "Education & Social Engagement"],
    missionObjectives: [
      "Prevent pollution – litter & microplastics (Luisa Galgani)",
      "Mobilization & engagement (Giovanna Chimini)",
      "Protect & restore marine and coastal ecosystems and biodiversity (Patrizio Mariani)",
    ],
    topicClusters: ["Pollution remediation", "Ocean literacy & citizen science"],
    technologyPillars: ["Collection", "Monitoring"],
    summary:
      "Launches coordinated riverine plastic barriers, smart fishing-for-litter incentives, and a schools observatory network across the North Sea basin.",
    funding: "LIFE Programme · Mission Ocean Flagship",
    budget: "€5.9M",
    missionKpis: ["Tonnes collected", "Citizen scientists engaged", "Hotspots mapped"],
    keywords: ["marine litter", "citizen science", "fishing for litter"],
    website: "https://northseaplasticsweep.org",
    partners: [
      { id: "northsea-cleanup", name: "North Sea Cleanup Alliance", acronym: "NSCA", country: "Netherlands", type: "NGO", role: "Lead", website: "https://nscleanup.eu" },
      { id: "scottish-marine-institute", name: "Scottish Marine Institute", acronym: "SMI", country: "United Kingdom", type: "Research Institute", role: "Partner", website: "https://smi.ac.uk" },
      {
        id: "hamburg-circular-tech",
        name: "Hamburg Circular Tech",
        acronym: "HCT",
        country: "Germany",
        type: "SME",
        role: "Partner",
        website: "https://hct.de",
      },
      { id: "ocean-citizens-network", name: "Ocean Citizens Network", acronym: "OCN", country: "Netherlands", type: "Civil Society", role: "Partner", website: "https://oceancitizens.eu" },
    ],
    insights: {
      technologyHighlights: ["AI litter recognition", "Dynamic marine litter routing"],
      engagementActions: ["Citizen regatta clean-ups", "Schools ocean labs"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€4.4M",
      missionZoneFocus: "19 ports & rivers",
      technologyFocus: "Barrier networks & citizen sensing",
    },
  },
  {
    id: "PRJ-2023-030",
    title: "Iberian Citizen Ocean Labs",
    acronym: "ICO-Labs",
    status: "Ongoing",
    startDate: "2023-05-10",
    endDate: "2026-05-09",
    startYear: 2023,
    missionZone: "Atlantic-Mediterranean Interface",
    leadPartner: "Barcelona Digital Ocean Hub",
    leadCountry: "Spain",
    missionPillars: ["Education & Social Engagement", "Human Health", "Environmental"],
    missionObjectives: [
      "Raising awareness (Philippe Vallette)",
      "Mobilization & engagement (Giovanna Chimini)",
      "Protect & restore marine and coastal ecosystems and biodiversity (Patrizio Mariani)",
    ],
    topicClusters: ["Ocean literacy & citizen science", "Habitat restoration"],
    technologyPillars: ["Monitoring", "Collection"],
    summary:
      "Creates coastal living labs in Spain and Portugal with citizen ocean observations, habitat restoration sprints, and blue health campaigns.",
    funding: "European Innovation Ecosystems · Mission Citizens",
    budget: "€3.6M",
    missionKpis: ["Citizen datasets submitted", "Habitats restored", "Public awareness index"],
    keywords: ["living labs", "community science", "blue health"],
    website: "https://iberianoceanlabs.eu",
    partners: [
      {
        id: "barcelona-digital-ocean-hub",
        name: "Barcelona Digital Ocean Hub",
        acronym: "BDOH",
        country: "Spain",
        type: "Innovation Hub",
        role: "Lead",
        website: "https://barcelonadoceanhub.org",
      },
      { id: "porto-blue-health", name: "Porto Blue Health Institute", acronym: "PBHI", country: "Portugal", type: "Research Institute", role: "Partner", website: "https://pbhi.pt" },
      { id: "ocean-citizens-network", name: "Ocean Citizens Network", acronym: "OCN", country: "Netherlands", type: "Civil Society", role: "Partner", website: "https://oceancitizens.eu" },
      { id: "lisbon-science-museum", name: "Lisbon Science Museum", acronym: "MUCI", country: "Portugal", type: "Cultural Institution", role: "Partner", website: "https://www.museudaciencia.pt" },
    ],
    insights: {
      technologyHighlights: ["Citizen sensing mobile apps", "Low-cost reef restoration kits"],
      engagementActions: ["Blue health festivals", "Community science residencies"],
    },
    comparison: {
      durationMonths: 36,
      euContribution: "€2.9M",
      missionZoneFocus: "8 coastal living labs",
      technologyFocus: "Citizen sensing & restoration kits",
    },
  },
];
